package org.mimicry;

import java.io.IOException;

public class Main {
    public static void main(String[] args) throws IOException, InterruptedException {
        String inputsDir = "inputs"; // hand-written inputs
        String workDir = "work";     // generated artifacts (gitignored)

        // Given by user
        String programPathOPC = inputsDir + "/programOP.c"; // LLVM INPUT
        String programPathPUAC = inputsDir + "/programPUA.c"; // LLVM INPUT
        String sigmaFilePath = inputsDir + "/sigma.txt"; // SIGMA PAIRS

        // Check if the number of arguments is correct
        if (args.length >= 3) {
            programPathOPC = args[0];
            programPathPUAC = args[1];
            sigmaFilePath = args[2];
        } else {
            System.out.println("Using default paths");
        }

        for (String arg : args) {
            if (arg.equals("--no-render")) {
                Automata.renderEnabled = false;
            }
        }

        // Pre existing Files (generated by the analyze step)
        String dotFilePathOP = workDir + "/cfgs/mainOP.dot"; // LLVM OUTPUT
        String dotFilePathPUA = workDir + "/cfgs/mainPUA.dot"; // LLVM OUTPUT

        String llvmAnalysisPathOP = workDir + "/temps/defUseOP.txt"; // LLVM OUTPUT
        String llvmAnalysisPathPUA = workDir + "/temps/defUsePUA.txt"; // LLVM OUTPUT

        String llvmIRPathOP = workDir + "/temps/programOP.ll"; // LLVM OUTPUT
        String llvmIRPUA = workDir + "/temps/programPUA.ll"; // LLVM OUTPUT

        // Files that will be created during the process
        String OPvariableDataPath = workDir + "/temps/OP_defUseInfoParsed.txt";
        String PUAvariableDataPath = workDir + "/temps/PUA_defUseInfoParsed.txt";

        // PUA Processing
        DOTParser llvmPUAParsed = new DOTParser(dotFilePathPUA, llvmAnalysisPathPUA, "PUA");
        LLVMProcessing transformedPUA = new LLVMProcessing(llvmPUAParsed, llvmIRPUA, programPathPUAC, "PUA");

        // OP Processing
        DOTParser llvmOPParsed = new DOTParser(dotFilePathOP, llvmAnalysisPathOP, "OP");
        LLVMProcessing transformedOP = new LLVMProcessing(llvmOPParsed, llvmIRPathOP, programPathOPC, "OP");

        // Construct monitor and run program.cpp
        Automata mimicryMonitor = new MonitorConstructor(transformedOP, transformedPUA, sigmaFilePath,
                OPvariableDataPath, PUAvariableDataPath);
        mimicryMonitor.generateRender("MM", "monitor");
    }
}